import type { InventoryProduct } from "./inventory.types";

export const INVENTORY_MOCK: InventoryProduct[] = [
  {
    id: 1,
    nombre: "Leche entera",
    sku: "LEC-001",
    categoria: "Lácteos",
    familia: "Leche",
    variante: "Entera",
    presentacion: "1 L",
    costoARS: 45,
    precioARS: 65,
    stockActual: 150,
    stockMinimo: 50,
    produccionPropia: true,
  },
  {
    id: 2,
    nombre: "Queso fresco",
    sku: "QUE-002",
    categoria: "Lácteos",
    familia: "Queso",
    variante: "Fresco",
    presentacion: "500 g",
    costoARS: 85,
    precioARS: 120,
    stockActual: 45,
    stockMinimo: 30,
    produccionPropia: true,
  },
  {
    id: 3,
    nombre: "Yogurt natural",
    sku: "YOG-003",
    categoria: "Lácteos",
    familia: "Yogurt",
    variante: "Natural",
    presentacion: "1 L",
    costoARS: 28,
    precioARS: 40,
    stockActual: 200,
    stockMinimo: 80,
    produccionPropia: true,
  },
  {
    id: 4,
    nombre: "Mantequilla",
    sku: "MAN-004",
    categoria: "Lácteos",
    familia: "Mantequilla",
    variante: null,
    presentacion: "250 g",
    costoARS: 55,
    precioARS: 75,
    stockActual: 80,
    stockMinimo: 40,
    produccionPropia: true,
  },
  {
    id: 5,
    nombre: "Queso mozzarella",
    sku: "QUE-005",
    categoria: "Lácteos",
    familia: "Queso",
    variante: "Mozzarella",
    presentacion: "1 kg",
    costoARS: 140,
    precioARS: 190,
    stockActual: 25,
    stockMinimo: 20,
    produccionPropia: false,
  },
  {
    id: 6,
    nombre: "Crema de leche",
    sku: "CRE-006",
    categoria: "Lácteos",
    familia: "Crema",
    variante: null,
    presentacion: "500 ml",
    costoARS: 38,
    precioARS: 55,
    stockActual: 120,
    stockMinimo: 60,
    produccionPropia: true,
  },
  {
    id: 7,
    nombre: "Leche descremada",
    sku: "LEC-007",
    categoria: "Lácteos",
    familia: "Leche",
    variante: "Descremada",
    presentacion: "1 L",
    costoARS: 48,
    precioARS: 68,
    stockActual: 15,
    stockMinimo: 50,
    produccionPropia: true,
  },
  {
    id: 8,
    nombre: "Queso parmesano",
    sku: "QUE-008",
    categoria: "Lácteos",
    familia: "Queso",
    variante: "Parmesano",
    presentacion: "200 g",
    costoARS: 95,
    precioARS: 135,
    stockActual: 35,
    stockMinimo: 25,
    produccionPropia: false,
  },
  {
    id: 9,
    nombre: "Yogurt vainilla",
    sku: "YOG-009",
    categoria: "Lácteos",
    familia: "Yogurt",
    variante: "Vainilla",
    presentacion: "1 L",
    costoARS: 30,
    precioARS: 42,
    stockActual: 88,
    stockMinimo: 40,
    produccionPropia: true,
  },
  {
    id: 10,
    nombre: "Cultivo lácteo (insumo)",
    sku: "INS-010",
    categoria: "Materia prima",
    familia: "Insumos",
    variante: null,
    presentacion: "sobre",
    costoARS: 120,
    precioARS: 0,
    stockActual: 40,
    stockMinimo: 10,
    produccionPropia: false,
  },
  {
    id: 11,
    nombre: "Cajas de cartón",
    sku: "EMP-011",
    categoria: "Empaque",
    familia: "Embalaje",
    variante: null,
    presentacion: "unidad",
    costoARS: 12,
    precioARS: 0,
    stockActual: 500,
    stockMinimo: 100,
    produccionPropia: false,
  },
];
